services:
  - type: web
    name: rate-limiter
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rate-limiter-db
          property: connectionString
      - key: NODE_ENV
        value: production
  - type: psql
    name: rate-limiter-db
    plan: free
